name: Build and push image

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Quay.io Container Registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}
      -
        name: Build go app image
        uses: docker/build-push-action@v2
        with:
          context: go
          push: true
          tags: |
            quay.io/acend/example-web-go:pr-${{ github.event.pull_request.number }}
      -
        name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'quay.io/acend/example-web-go:pr-${{ github.event.pull_request.number }}'
          format: 'table'
          output: 'trivy-results.txt'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os'
          severity: 'CRITICAL,HIGH'
      -
        name: Archive vulnerability scan results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results-main
          path: trivy-results.txt
      -
        name: Build python app image
        uses: docker/build-push-action@v2
        with:
          context: python
          push: true
          tags: |
            quay.io/acend/example-web-python:pr-${{ github.event.pull_request.number }}
      -
        name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'quay.io/acend/example-web-python:pr-${{ github.event.pull_request.number }}'
          format: 'table'
          output: 'trivy-results.txt'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os'
          severity: 'CRITICAL,HIGH'
      -
        name: Archive vulnerability scan results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results-main
          path: trivy-results.txt
