name: PR cleanup
on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: 'ubuntu-latest'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      -
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            golang:
              - 'go/**'
            python:
              - 'python/**'
      -
        name: Delete go tag on Quay
        if: steps.filter.outputs.golang == 'true'
        id: delete_go_tag
        env:
          PR_NUMBER: '${{ github.event.pull_request.number }}'
          QUAYIO_API_TOKEN: '${{ secrets.QUAYIO_API_TOKEN }}'
        run: curl -X DELETE -H "Authorization: Bearer ${QUAYIO_API_TOKEN}" "https://quay.io/api/v1/repository/acend/example-web-go/tag/pr-${PR_NUMBER}"
      -
        name: Delete python tag on Quay
        if: steps.filter.outputs.python == 'true'
        id: delete_python_tag
        with:
          files: python/**
        env:
          PR_NUMBER: '${{ github.event.pull_request.number }}'
          QUAYIO_API_TOKEN: '${{ secrets.QUAYIO_API_TOKEN }}'
        run: curl -X DELETE -H "Authorization: Bearer ${QUAYIO_API_TOKEN}" "https://quay.io/api/v1/repository/acend/example-web-python/tag/pr-${PR_NUMBER}"
